version: '3.1'

services:
  s_registry:
    image: registry:2
    container_name: c_registry
    ports:
      - 5000:5000
    restart: always
    networks:
      - custom_net

networks:
  custom_net:
   external: true
 
    

