version: '3.7'

services:
  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 9090:15672
    volumes:
      - /mnt/nfs_shares/docker_app_data/rabbitmq:/var/lib/rabbitmq
    networks:
     - net_all
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
   net_all:
     external: true

