services:
   portainer:
     container_name: c_portainer
     image: portainer/portainer-ce
     ports:
       - 8000:8000
       - 9000:9000
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /mnt/nfs_shares/docker_app_data/portainer:/data
     networks:
       - custom_net


networks:
  custom_net:
    external: true

